# End to End Text-Summarization Project

## Workflow

1. Update config.yaml
2. Update params.yaml
3. Update entity
4. Update the Configuration manager in src config
5. Update the conponents 
6. Update the pipline
7. Update the main.py
8. Update the app.py
